name = "MeltingPot"
uuid = "fb9bebcb-6100-4ece-a43c-017a2832c36a"
authors = ["Paul Shen <pxshen@alumni.stanford.edu>"]
version = "0.1.0"

[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
[compat]
ChainRulesCore = "1,5"
DataStructures = "0.18"
julia="1"